require "nvb.options"
require "nvb.keymaps"
require "nvb.plugins"
require "nvb.colorscheme"
require "nvb.cmp"
require "nvb.lsp"
require "nvb.telescope"
require "nvb.treesitter"
require "nvb.lualine"
require "nvb.autopairs"
require "nvb.comments"
require "nvb.startify"
require "nvb.gitlines"
require "nvb.nvim-tree"
require "nvb.bufferline"
require "nvb.float_term"
require "nvb.project"
require "nvb.neogit"
require "nvb.neogen"
require "nvb.which-key"

vim.cmd [[hi Normal guibg=NONE ctermbg=NONE]]
